services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: database_flask_exam
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: company
    ports:
      - 80:80
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: database_mysql_exam
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: database_phpmyadmin_exam
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80

  arangodb:
    image: arangodb:latest
    container_name: database_arangodb_exam
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data:/var/lib/arangodb3
    ports:
      - 8529:8529

  arangodb2:
    image: arangodb:latest
    container_name: database_arangodb_exam_2
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb2_data:/var/lib/arangodb3
    ports:
      - 8530:8529 # Map internal port 8529 to external port 8530

  redis:
    image: redis:latest
    container_name: database_redis_exam
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  arangodb_data:
  arangodb2_data:  # Added a separate volume for arangodb2
  redis_data:
